# Generated by Django 6.0.2 on 2026-02-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0009_alter_deliveryagentperformance_id_and_more'),
        ('deliveryAgent', '0010_alter_deliveryagentperformance_id_and_more'),
    ]

    operations = [
    ]
